// resources/js/Components/ui/NavLink.tsx
import { InertiaLinkProps, Link } from "@inertiajs/react";

import { cn } from "@/utils/tailwind";

export default function NavLink({
    children,
    active = false,
    ...rest
}: InertiaLinkProps & { href: string; active: boolean }) {
    return (
        <Link
            className={cn(
                "inline-flex items-center border-b-2 px-1 pt-1",
                active
                    ? "border-indigo-400 text-sm font-medium leading-5 text-gray-900 transition duration-150 ease-in-out focus:border-indigo-700 focus:outline-none dark:border-indigo-600 dark:text-gray-100"
                    : "group border-transparent text-sm font-medium leading-5 transition-all duration-300 ease-in-out"
            )}
            {...rest}
        >
            <span className="bg-gradient-to-r from-indigo-200 via-violet-400 to-cyan-200 bg-[length:0%_2px] bg-left-bottom bg-no-repeat text-cyan-500 transition-all duration-500 ease-out group-hover:bg-[length:100%_2px] group-hover:text-indigo-600">
                {children}
            </span>
        </Link>
    );
}

// resources/_js/Components/NavLink.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Link } from '@inertiajs/vue3';

const props = defineProps<{
    href: string;
    active?: boolean;
}>();

const classes = computed(() =>
    props.active
        ? 'inline-flex items-center px-1 pt-1 border-b-2 border-indigo-400 dark:border-indigo-600 text-sm font-medium leading-5 text-gray-900 dark:text-gray-100 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out'
        : 'inline-flex items-center px-1 pt-1 border-b-2 border-transparent text-sm font-medium leading-5 transition-all duration-300 ease-in-out group'
);
</script>

<template>
    <Link :href="href" :class="classes">
    <span
        class="text-cyan-500 group-hover:text-indigo-600 bg-left-bottom bg-gradient-to-r from-indigo-200 via-violet-400 to-cyan-200 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out">
        <slot />
    </span>
    </Link>
</template>
