// resources/js/Components/ui/ResponsiveNavLink.tsx
import { cn } from "@/utils/tailwind";
import { InertiaLinkProps, Link } from "@inertiajs/react";
import type { ClassValue } from "clsx";

export const responsiveLinkClasses = (
    active: boolean,
    className: ClassValue = ""
) =>
    cn(
        "w-full",
        "flex",
        "items-start",
        "ps-3",
        "pe-4",
        "py-2",
        "border-l-4",
        active
            ? "border-indigo-400 text-indigo-700 bg-indigo-50 focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700"
            : "border-transparent text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300",
        "text-base",
        "font-medium",
        "focus:outline-none",
        "transition duration-150",
        "ease-in-out",
        className
    );

export default function ResponsiveNavLink({
    active = false,
    className = "",
    children,
    ...props
}: InertiaLinkProps & { active?: boolean }) {
    return (
        <Link {...props} className={responsiveLinkClasses(active, className)}>
            {children}
        </Link>
    );
}

// resources/js/Components/ResponsiveNavLink.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Link } from '@inertiajs/vue3';

const props = defineProps<{
    href: string;
    active?: boolean;
}>();

const classes = computed(() =>
    props.active
        ? 'block w-full pl-3 pr-4 py-2 border-l-4 border-indigo-400 dark:border-indigo-600 text-left text-base font-medium text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-900/50 focus:outline-none focus:text-indigo-800 dark:focus:text-indigo-200 focus:bg-indigo-100 dark:focus:bg-indigo-900 focus:border-indigo-700 dark:focus:border-indigo-300 transition duration-150 ease-in-out'
        : 'block w-full pl-3 pr-4 py-2 border-l-4 border-transparent text-left text-base font-medium text-gray-600 transition-all duration-300 ease-in-out group'
);
</script>

<template>
    <Link :href="href" :class="classes">
    <span
        class="text-cyan-500 group-hover:text-indigo-600 bg-left-bottom bg-gradient-to-r from-indigo-200 via-violet-400 to-cyan-200 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out">
        <slot />
    </span>
    </Link>
</template>
